### ISSUE TITLE
[Feature request]Activate brake at negative throttle

### ISSUE THREAD

**Issue by laci200270** [sim-/tgy#103]
It would be good if there would be an option to activate brake below -10%.(there is an option in Turningy 9x which can set thr to -30%) this would be good to prevent accidentaly brake when I pull the joy down at landing

**Comment by ahalekelly** [comment]
You can do this with the LOW_BRAKE setting, as long as you're not using bidirectional control.

**Comment by laci200270** [comment]
Thank you
