### ISSUE TITLE
Today, latest master for BS_Nfet did not work on HK F-30a ESC's

### ISSUE THREAD

**Issue by Ozzy33** [sim-/tgy#106]
FYI, I flashed some HK F-30a esc's with the latest master (BS_Nfet) using rapid-flash today and got no motor spin. I then tried 9-12-2015 version and works fine. I used the latest master about 3 weeks ago without any problems on same esc's. Thanks for excellent work!

**Comment by sim-** [comment]
Hello! There was literally no output change for bs_nfet since the 2015-09-12 tag until very recently, so likely this was a problem with the rapidflash build source or similar.
