### ISSUE TITLE
Problem with the Afro ESC USB Programming Tool

### ISSUE THREAD

**Issue by gurupras** [sim-/tgy#117]
Hi,

I'm really sorry if this is the wrong place to be posting in. Hobbyking directed me to this page and asked me to post my query here.

I have the USB tool which I used to flash my ESCs. I successfully flashed 2 ESCs after which Windows complains that the USB tool has malfunctioned.

I used a current limiting circuit with my 11.1V lipo and a 12V-20W bulb in series. Like i said, I successfully flashed 2 ESCs but then the device would just not be recognized on Windows and Linux.
Linux complains saying: `usb 1-5: device descriptor read/8, error -61`

Is there anything I can do to get this device working again? I'd hate to have to spend another $15 on procuring this just to flash the remaining 2 ESCs

**Comment by sim-** [comment]
Hi there! Unfortunately, I had nothing to do with the design of that tool. All I did was reverse-engineer another tool, which was apparently cloned to make that one. I haven't managed to break any of mine yet, but I suspect the lack of isolation or current limiting on the I/O ports. It might be a good idea to add some resistors, or best of all, perhaps use it with a USB isolator, which have finally become relatively inexpensive on eBay, etc. The one you have sounds pretty dead. :(
