### ISSUE TITLE
MOTOR_BRAKE and BEACON_IDLE result in assembler error

### ISSUE THREAD

**Issue by ahalekelly** [sim-/tgy#120]
When yo set MOTOR_BRAKE = 1 and BEACON_IDLE = 1, both AVRA and avrasm2 crash. AVRA says `Error   : Branch out of range (-64 <= k <= 63)`. Any idea what's causing this?

**Comment by sim-** [comment]
Hello! This should be (finally) fixed now. Sorry about the delay!

The error is just because AVR only supports branching to ±64 words from the "brxx" type of instructions, and enabling those features made the branch too far to reach.
